Stable branch
SnowflakePowered/winfsp-rs pull request #5
Opened 2023-04-06 16:00 UTC by TimeEngineer

Hi, I would like to use this crate with stable `rust`

2023-04-06 16:01 UTC, TimeEngineer commented on winfsp-sys/src/bindings.rs
Is this needed to maintain such file ?

2023-04-24 04:17 UTC, chyyran commented
Hi, sorry for the delayed response. My GitHub notifications have not been working lately. 

I will review this within the week.

2023-04-24 04:28 UTC, chyyran requested changes
Most of the nightly features used have been stabilized since this crate was released, which is good.

Please add a cfg out for strict_provenance semantics when compiling under nightly.

2023-04-24 04:28 UTC, chyyran commented on winfsp-sys/src/bindings.rs
Yes, for docs.rs purposes.

2023-04-24 04:28 UTC, chyyran commented on winfsp/src/lib.rs
> +pub use windows::*;
This import doesn't seem needed. If it is, do not glob import `windows`.

2023-04-24 04:28 UTC, chyyran commented on winfsp/src/vsb.rs
> +    pub fn is_empty(&self) -> bool {
This isn't used anywhere and doesn't make sense for the semantics of `VariableSizedBox`

2023-04-24 04:28 UTC, chyyran commented on winfsp/src/filesystem/internals/fileinfo.rs
> +                    .wrapping_offset(1)
Please add a cfg here for strict provenance semantics if available.

2023-04-24 05:31 UTC, closed without merging

2023-04-24 05:32 UTC, chyyran commented
Addressed in #8. Thanks for your contribution.

You can disable usage of nightly features like so:

```toml
[dependencies.winfsp]
default-features = false
# notify if you need filesystem notifications, delayload is needed for build-time helpers.
features = ["notify", "delayload"]
```